version: "3.7"
services:
#  springapp:
#    build: .
#    container_name: cadcli
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cadcli
#    ports:
#      - 1111:1111
#    restart: always
#    depends_on:
#      - db
  db:
    image: postgres:alpine3.18
    container_name: db
    environment:
      - POSTGRES_USER=fabianocampos
      - POSTGRES_PASSWORD=campos
      - POSTGRES_DB=cadcli
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  db:
    driver: local